
#
# This file is the default set of rules to compile a Pebble project.
#
# Feel free to customize this to your needs.
#

top = '.'
out = 'build'

def options(ctx):
    ctx.load('pebble_sdk')

def configure(ctx):
    ctx.load('pebble_sdk')

def build(ctx):
    ctx.load('pebble_sdk')

    ctx.pbl_program(source=ctx.path.ant_glob('src/**/*.c'),
                    target='pebble-app.elf')

    # Concatenate all JS files into pebble-js-app.js prior to building.
    all_js = "\n".join([node.read() for node in ctx.path.ant_glob('src/js/**/*.js', excl='src/js/pebble-js-app.js')])
    out_js_node = ctx.path.make_node('src/js/pebble-js-app.js')
    out_js_node.write(all_js)

    ctx.pbl_bundle(elf='pebble-app.elf', js=out_js_node)